// Copyright (c) 2015-present Peter Kieltyka (https://github.com/pkieltyka), Google Inc.
// Originally derived from github.com/go-chi/chi (MIT License).

package radix

import (
	"fmt"
	"strings"
)

// Endpoint holds the payload value for a specific HTTP method on a node.
type Endpoint[V any] struct {
	Value         V
	Pattern       string
	AutoGenerated bool // true for auto-generated endpoints (e.g., HEAD from GET)
}

// Endpoints maps MethodTyp bitflags to their Endpoint.
type Endpoints[V any] map[MethodTyp]*Endpoint[V]

// Node represents a node in the radix tree. The tree stores opaque payload
// values of type V — the router defines what a payload is; the tree never
// inspects or invokes it.
type Node[V any] struct {
	// Typ is the node type (static, param, regexp, catch-all).
	Typ NodeTyp

	// Label is the first byte of the prefix (for fast edge lookup).
	Label byte

	// Prefix is the compressed path prefix stored in this node.
	Prefix string

	// Tail is the byte following a parameter segment (for scan optimization).
	Tail byte

	// ParamKey is the parameter name for param/regexp/catch-all nodes.
	ParamKey string

	// RegexpSeg is the parsed pattern segment for NtRegexp nodes.
	// Named RegexpSeg (not Regexp) to avoid confusing double-dereference
	// like node.Regexp.Regexp when accessing the compiled *regexp.Regexp.
	RegexpSeg *PatternSegment

	// Children holds child nodes, sorted by routing priority.
	Children [NtCatchAll + 1]Nodes[V]

	// Endpoints maps HTTP methods to their payloads.
	Endpoints Endpoints[V]
}

// NewTree returns an empty root node ready for InsertRoute.
func NewTree[V any]() *Node[V] {
	return &Node[V]{
		Typ:       NtStatic,
		Endpoints: make(Endpoints[V]),
	}
}

// newNode creates a new node of the given type with the specified prefix.
func newNode[V any](typ NodeTyp, prefix string) *Node[V] {
	var label byte
	if len(prefix) > 0 {
		label = prefix[0]
	}
	return &Node[V]{
		Typ:       typ,
		Label:     label,
		Prefix:    prefix,
		Endpoints: make(Endpoints[V]),
	}
}

// InsertRoute adds a route pattern and payload value to the tree.
// Returns the leaf node and an error if the pattern conflicts with existing routes.
// If autoGenerated is true, the endpoint is marked as auto-generated and can be
// overwritten by explicit (non-auto-generated) registrations.
func (n *Node[V]) InsertRoute(method MethodTyp, pattern string, value V, autoGenerated ...bool) (*Node[V], error) {
	autoGen := len(autoGenerated) > 0 && autoGenerated[0]
	search := pattern

	for {
		// Handle root node
		if len(search) == 0 {
			if err := n.setEndpoint(method, value, pattern, autoGen); err != nil {
				return nil, err
			}
			return n, nil
		}

		// Find or create child node
		var label byte
		if search[0] == '{' {
			label = '{'
		} else {
			label = search[0]
		}

		var child *Node[V]

		// Look for matching edge
		if search[0] == '{' {
			// Parameter segment — parse it
			seg, err := patNextSegment(search)
			if err != nil {
				return nil, err
			}
			segmentPattern := search[:len(search)-len(seg.Suffix)]

			child, err = n.findOrUpdateParamChild(seg, segmentPattern, pattern)
			if err != nil {
				return nil, err
			}

			if child == nil {
				child = &Node[V]{
					Typ:       seg.Typ,
					Label:     '{',
					Prefix:    segmentPattern,
					Tail:      seg.TailByte,
					ParamKey:  seg.ParamKey,
					Endpoints: make(Endpoints[V]),
				}

				if seg.Typ == NtRegexp {
					child.RegexpSeg = &seg
				}

				n.addChild(child)
			}

			n = child
			search = seg.Suffix
			continue
		}

		// Static segment — find edge by label
		child = n.Children[NtStatic].FindEdge(label)

		if child != nil {
			// Existing edge found — compute longest common prefix
			commonLen := longestPrefix(search, child.Prefix)

			if commonLen == len(child.Prefix) {
				// Entire child prefix matches — descend

				n = child
				search = search[commonLen:]
				continue
			}

			// Partial match — split the node
			splitChild := &Node[V]{
				Typ:       NtStatic,
				Label:     child.Prefix[0],
				Prefix:    child.Prefix[:commonLen],
				Endpoints: make(Endpoints[V]),
			}

			// Replace in parent BEFORE modifying child (child is a pointer
			// in n.Children, so modifying its Label would break the lookup).
			n.replaceChild(child.Label, splitChild)

			// Now update existing child to be the suffix
			child.Label = child.Prefix[commonLen]
			child.Prefix = child.Prefix[commonLen:]

			splitChild.addChild(child)

			n = splitChild
			search = search[commonLen:]
			continue
		}

		// No matching edge — create new child
		child = &Node[V]{
			Typ:       NtStatic,
			Label:     label,
			Prefix:    search,
			Endpoints: make(Endpoints[V]),
		}

		remaining := search

		// Check if the new static segment contains a parameter
		braceIdx := strings.IndexByte(remaining, '{')
		if braceIdx >= 0 {
			child.Prefix = remaining[:braceIdx]
			n.addChild(child)

			n = child
			search = remaining[braceIdx:]
			continue
		}

		child.Prefix = remaining
		n.addChild(child)
		if err := child.setEndpoint(method, value, pattern, autoGen); err != nil {
			return nil, err
		}
		return child, nil
	}
}

// findOrUpdateParamChild finds an existing parameter child that matches the
// given segment, or returns nil if none exists. For regexp nodes with a
// matching pattern, it may update the existing node's TailByte if previously
// unset (hence "OrUpdate" in the name).
func (n *Node[V]) findOrUpdateParamChild(seg PatternSegment, segmentPattern, fullPattern string) (*Node[V], error) {
	children := n.Children[seg.Typ]

	switch seg.Typ {
	case NtParam, NtCatchAll:
		if len(children) == 0 {
			return nil, nil
		}

		existing := children[0]
		if existing.ParamKey != seg.ParamKey {
			return nil, conflictingParameterError(
				seg.Typ, seg.ParamKey, existing.ParamKey, existing.firstEndpointPattern(), fullPattern,
			)
		}
		return existing, nil

	case NtRegexp:
		for _, ch := range children {
			if ch.RegexpSeg == nil || ch.RegexpSeg.Regexp == nil {
				continue
			}

			sameMatcher := ch.RegexpSeg.Regexp.String() == seg.Regexp.String()
			if !sameMatcher {
				continue
			}

			if ch.ParamKey != seg.ParamKey {
				return nil, conflictingParameterError(
					seg.Typ, seg.ParamKey, ch.ParamKey, ch.firstEndpointPattern(), fullPattern,
				)
			}

			if ch.Tail != 0 && seg.TailByte != 0 && ch.Tail != seg.TailByte {
				return nil, fmt.Errorf(
					"radix: conflicting regexp tail %q with existing %q; existing route %q; new route %q",
					seg.TailByte, ch.Tail, ch.firstEndpointPattern(), fullPattern)
			}

			if ch.Tail == 0 && seg.TailByte != 0 {
				ch.Tail = seg.TailByte
			}

			return ch, nil
		}

		if len(children) > 0 {
			return nil, fmt.Errorf(
				"radix: conflicting regexp segment %q; existing route %q; "+
					"new route %q; only one regexp matcher is allowed at the same path level",
				segmentPattern, children[0].firstEndpointPattern(), fullPattern)
		}
	}

	return nil, nil
}

func conflictingParameterError(typ NodeTyp, newKey, existingKey, existingPattern, newPattern string) error {
	return fmt.Errorf(
		"radix: conflicting %s parameter %q with existing %q; existing route %q; "+
			"new route %q; dynamic segments at the same path level must use the same parameter name",
		parameterKindName(typ), newKey, existingKey, existingPattern, newPattern)
}

func (n *Node[V]) firstEndpointPattern() string {
	if n == nil {
		return ""
	}
	for _, method := range []MethodTyp{
		MConnect, MDelete, MGet, MHead, MOptions, MPatch, MPost, MPut, MTrace, mStub,
	} {
		if ep, ok := n.Endpoints[method]; ok {
			return ep.Pattern
		}
	}
	for _, method := range AllMethods() {
		if ep, ok := n.Endpoints[method]; ok {
			return ep.Pattern
		}
	}
	for _, children := range n.Children {
		for _, child := range children {
			if pattern := child.firstEndpointPattern(); pattern != "" {
				return pattern
			}
		}
	}
	return ""
}

func parameterKindName(t NodeTyp) string {
	switch t {
	case NtParam:
		return "path"
	case NtRegexp:
		return "regexp"
	case NtCatchAll:
		return "catch-all"
	default:
		return nodeTypName(t)
	}
}

// FindRoute traverses the tree to find the payload registered for the given
// method and path. It populates rctx with matched parameters.
// The boolean reports whether a route matched; when it is false,
// rctx.MethodNotAllowed tells a 404 apart from a 405.
func (n *Node[V]) FindRoute(rctx *RouteContext, method MethodTyp, path string) (V, bool) {
	v, found, _ := n.findRoute(rctx, method, path)
	return v, found
}

func (n *Node[V]) findRoute(rctx *RouteContext, method MethodTyp, path string) (v V, found, methodNotAllowed bool) {
	// Base case: path fully consumed
	if len(path) == 0 {
		if n.isLeaf() {
			if h, ok := n.resolveEndpoint(rctx, method); ok {
				return h, true, false
			}
			// Method not allowed — record allowed methods
			rctx.MethodNotAllowed = true
			return v, false, true
		}
		return v, false, false
	}

	// Search static children first (highest priority)
	for _, child := range n.Children[NtStatic] {
		if child.Label != path[0] {
			continue
		}

		if len(path) >= len(child.Prefix) && path[:len(child.Prefix)] == child.Prefix {
			h, ok, mna := child.findRoute(rctx, method, path[len(child.Prefix):])
			if ok || mna {
				return h, ok, mna
			}
		}
	}

	// Search regexp children
	for _, child := range n.Children[NtRegexp] {
		if child.RegexpSeg == nil || child.RegexpSeg.Regexp == nil {
			continue
		}

		remaining := path

		// If TailByte is set, limit the search to end at the tail boundary.
		// This prevents greedy regexes from consuming past the delimiter.
		searchStr := remaining
		if child.Tail != 0 {
			if tailIdx := strings.IndexByte(remaining, child.Tail); tailIdx >= 0 {
				searchStr = remaining[:tailIdx]
			}
		}

		loc := child.RegexpSeg.Regexp.FindStringIndex(searchStr)
		if loc == nil || loc[0] != 0 {
			continue
		}

		value := searchStr[loc[0]:loc[1]]
		if len(value) == 0 {
			continue // empty match — skip
		}
		rest := remaining[loc[1]:]

		rctx.Params.Add(child.ParamKey, value)
		h, ok, mna := child.findRoute(rctx, method, rest)
		if ok || mna {
			return h, ok, mna
		}
		// Backtrack: remove the param
		rctx.Params.Keys = rctx.Params.Keys[:len(rctx.Params.Keys)-1]
		rctx.Params.Values = rctx.Params.Values[:len(rctx.Params.Values)-1]
	}

	// Search param children
	for _, child := range n.Children[NtParam] {
		// Find the end of the parameter value
		var paramEnd int
		if child.Tail != 0 {
			paramEnd = strings.IndexByte(path, child.Tail)
			if paramEnd < 0 {
				// Tail byte not found — try consuming entire path
				paramEnd = len(path)
			}
		} else {
			// No tail byte — try next slash or end of path
			paramEnd = strings.IndexByte(path, '/')
			if paramEnd < 0 {
				paramEnd = len(path)
			}
		}

		if paramEnd == 0 {
			continue // Empty parameter value — skip
		}

		value := path[:paramEnd]
		rest := path[paramEnd:]

		rctx.Params.Add(child.ParamKey, value)
		h, ok, mna := child.findRoute(rctx, method, rest)
		if ok || mna {
			return h, ok, mna
		}
		// Backtrack
		rctx.Params.Keys = rctx.Params.Keys[:len(rctx.Params.Keys)-1]
		rctx.Params.Values = rctx.Params.Values[:len(rctx.Params.Values)-1]
	}

	// Search the catch-all child (lowest priority).
	// Invariant: a node has at most one catch-all child (enforced at insert,
	// since two catch-all patterns at the same position conflict), so index
	// directly rather than looping. Mirrors the upstream chi nds[0] form.
	if cc := n.Children[NtCatchAll]; len(cc) > 0 {
		child := cc[0]
		// Catch-all consumes the rest of the path
		rctx.Params.Add(child.ParamKey, path)
		if h, ok := child.resolveEndpoint(rctx, method); ok {
			return h, true, false
		}
		// Method not allowed on catch-all
		rctx.MethodNotAllowed = true
		rctx.Params.Keys = rctx.Params.Keys[:len(rctx.Params.Keys)-1]
		rctx.Params.Values = rctx.Params.Values[:len(rctx.Params.Values)-1]
		return v, false, true
	}

	return v, false, false
}

// isLeaf returns true if this node has at least one endpoint registered.
func (n *Node[V]) isLeaf() bool {
	return len(n.Endpoints) > 0
}

// resolveEndpoint returns the payload for the given method.
// Also collects allowed methods for 405 responses.
func (n *Node[V]) resolveEndpoint(rctx *RouteContext, method MethodTyp) (V, bool) {
	// Direct endpoint lookup
	if ep, ok := n.Endpoints[method]; ok {
		rctx.RoutePatterns = append(rctx.RoutePatterns, ep.Pattern)
		return ep.Value, true
	}

	// Stub endpoint (any method)
	if ep, ok := n.Endpoints[mStub]; ok {
		rctx.RoutePatterns = append(rctx.RoutePatterns, ep.Pattern)
		return ep.Value, true
	}

	// Collect allowed methods for 405 response
	for mtyp := range n.Endpoints {
		if mtyp != mStub {
			rctx.setMethodsAllowed(rctx.MethodsAllowed() | mtyp)
		}
	}

	var zero V
	return zero, false
}

// setEndpoint registers a payload for the given method on this node.
// If autoGenerated is true, the endpoint is marked as auto-generated.
// An auto-generated endpoint can be silently replaced by any new registration.
// A non-auto-generated (explicit) endpoint returns a duplicate error as before.
func (n *Node[V]) setEndpoint(method MethodTyp, value V, pattern string, autoGenerated bool) error {
	if existing, exists := n.Endpoints[method]; exists {
		if !existing.AutoGenerated {
			return fmt.Errorf("radix: duplicate route for method %s pattern %q (already registered as %q)",
				methodName(method), pattern, existing.Pattern)
		}
		// Auto-generated endpoint — allow overwrite.
	}

	n.Endpoints[method] = &Endpoint[V]{
		Value:         value,
		Pattern:       pattern,
		AutoGenerated: autoGenerated,
	}

	return nil
}

func methodName(method MethodTyp) string {
	if names := MethodTypToString(method); len(names) == 1 {
		return names[0]
	}
	return fmt.Sprintf("%d", method)
}

// addChild adds a child node and re-sorts the children of that type.
func (n *Node[V]) addChild(child *Node[V]) {
	n.Children[child.Typ] = append(n.Children[child.Typ], child)
	n.Children[child.Typ].Sort()
}

// replaceChild replaces a child that starts with the given label.
func (n *Node[V]) replaceChild(label byte, child *Node[V]) {
	for i, ch := range n.Children[NtStatic] {
		if ch.Label == label {
			n.Children[NtStatic][i] = child
			n.Children[NtStatic].Sort()
			return
		}
	}
}

// longestPrefix returns the length of the longest common prefix
// between two strings.
func longestPrefix(a, b string) int {
	n := min(len(a), len(b))
	for i := range n {
		if a[i] != b[i] {
			return i
		}
	}
	return n
}

func nodeTypName(t NodeTyp) string {
	switch t {
	case NtStatic:
		return "static"
	case NtRegexp:
		return "regexp"
	case NtParam:
		return "param"
	case NtCatchAll:
		return "catchAll"
	default:
		return "unknown"
	}
}
