// Copyright (c) 2015-present Peter Kieltyka (https://github.com/pkieltyka), Google Inc.
// Originally derived from github.com/go-chi/chi (MIT License).

package radix

import (
	"fmt"
	"net/url"
	"strings"
	"unicode/utf8"

	"github.com/credo-go/credo/internal/wirepath"
)

// Endpoint holds the payload value for a specific HTTP method on a node.
//
// Parameter names belong to the endpoint, not to the tree: the tree captures
// values positionally while matching, and the matched endpoint's ParamKeys
// name them. Two endpoints may therefore share a dynamic node under different
// names, and a name-stripped shape ("/users/{}") identifies a node.
type Endpoint[V any] struct {
	Value         V
	Pattern       string
	AutoGenerated bool // true for auto-generated endpoints (e.g., HEAD from GET)

	// ParamKeys lists the endpoint's parameter names in capture order — one
	// per dynamic segment of Pattern, from left to right.
	ParamKeys []string
}

// Endpoints maps MethodTyp bitflags to their Endpoint.
type Endpoints[V any] map[MethodTyp]*Endpoint[V]

// Node represents a node in the radix tree. The tree stores opaque payload
// values of type V — the router defines what a payload is; the tree never
// inspects or invokes it.
type Node[V any] struct {
	// Typ is the node type (static, param, regexp, catch-all).
	Typ NodeTyp

	// Label is the first byte of the prefix (for fast edge lookup).
	Label byte

	// Prefix is the compressed path prefix stored in this node. Dynamic nodes
	// hold the name-stripped segment shape ("{}", "{:regex}", "{...}"), since
	// parameter names live on endpoints.
	Prefix string

	// Tail is the byte following a parameter segment (for scan optimization).
	Tail byte

	// RegexpSeg is the parsed pattern segment for NtRegexp nodes.
	// Named RegexpSeg (not Regexp) to avoid confusing double-dereference
	// like node.Regexp.Regexp when accessing the compiled *regexp.Regexp.
	RegexpSeg *PatternSegment

	// Children holds child nodes, sorted by routing priority.
	Children [NtCatchAll + 1]Nodes[V]

	// Endpoints maps HTTP methods to their payloads.
	Endpoints Endpoints[V]
}

// NewTree returns an empty root node ready for InsertRoute.
func NewTree[V any]() *Node[V] {
	return &Node[V]{
		Typ:       NtStatic,
		Endpoints: make(Endpoints[V]),
	}
}

// InsertRoute adds a route pattern and payload value to the tree.
// Returns the leaf node and an error if the pattern conflicts with existing routes.
// If autoGenerated is true, the endpoint is marked as auto-generated and can be
// overwritten by explicit (non-auto-generated) registrations.
func (n *Node[V]) InsertRoute(method MethodTyp, pattern string, value V, autoGenerated ...bool) (*Node[V], error) {
	autoGen := len(autoGenerated) > 0 && autoGenerated[0]
	search, err := canonicalPattern(pattern)
	if err != nil {
		return nil, err
	}
	var paramKeys []string // endpoint-owned names, in capture order

	for {
		// Handle root node
		if len(search) == 0 {
			if err := n.setEndpoint(method, value, pattern, paramKeys, autoGen); err != nil {
				return nil, err
			}
			return n, nil
		}

		// Find or create child node
		var label byte
		if search[0] == '{' {
			label = '{'
		} else {
			label = search[0]
		}

		var child *Node[V]

		// Look for matching edge
		if search[0] == '{' {
			// Parameter segment — parse it
			seg, err := patNextSegment(search)
			if err != nil {
				return nil, err
			}
			segmentPattern := search[:len(search)-len(seg.Suffix)]
			paramKeys = append(paramKeys, seg.Name)

			child, err = n.findOrUpdateParamChild(seg, segmentPattern, pattern)
			if err != nil {
				return nil, err
			}

			if child == nil {
				child = &Node[V]{
					Typ:       seg.Kind,
					Label:     '{',
					Prefix:    segmentShape(seg),
					Tail:      seg.TailByte,
					Endpoints: make(Endpoints[V]),
				}

				if seg.Kind == NtRegexp {
					child.RegexpSeg = &seg
				}

				n.addChild(child)
			}

			n = child
			search = seg.Suffix
			continue
		}

		// Static segment — find edge by label
		child = n.Children[NtStatic].FindEdge(label)

		if child != nil {
			// Existing edge found — compute longest common prefix
			commonLen := longestPrefix(search, child.Prefix)

			if commonLen == len(child.Prefix) {
				// Entire child prefix matches — descend

				n = child
				search = search[commonLen:]
				continue
			}

			// Partial match — split the node
			splitChild := &Node[V]{
				Typ:       NtStatic,
				Label:     child.Prefix[0],
				Prefix:    child.Prefix[:commonLen],
				Endpoints: make(Endpoints[V]),
			}

			// Replace in parent BEFORE modifying child (child is a pointer
			// in n.Children, so modifying its Label would break the lookup).
			n.replaceChild(child.Label, splitChild)

			// Now update existing child to be the suffix
			child.Label = child.Prefix[commonLen]
			child.Prefix = child.Prefix[commonLen:]

			splitChild.addChild(child)

			n = splitChild
			search = search[commonLen:]
			continue
		}

		// No matching edge — create new child
		child = &Node[V]{
			Typ:       NtStatic,
			Label:     label,
			Prefix:    search,
			Endpoints: make(Endpoints[V]),
		}

		remaining := search

		// Check if the new static segment contains a parameter
		braceIdx := strings.IndexByte(remaining, '{')
		if braceIdx >= 0 {
			child.Prefix = remaining[:braceIdx]
			n.addChild(child)

			n = child
			search = remaining[braceIdx:]
			continue
		}

		child.Prefix = remaining
		n.addChild(child)
		if err := child.setEndpoint(method, value, pattern, paramKeys, autoGen); err != nil {
			return nil, err
		}
		return child, nil
	}
}

// segmentShape returns the name-stripped shape of a dynamic segment, the
// identity a dynamic node carries: "{}" for a parameter, "{:regex}" for a
// regexp-constrained parameter and "{...}" for a catch-all.
func segmentShape(seg PatternSegment) string {
	switch seg.Kind {
	case NtRegexp:
		return "{:" + seg.RegexpSource + "}"
	case NtCatchAll:
		return "{...}"
	default:
		return "{}"
	}
}

// FindEndpoint walks the tree read-only along pattern, using the same
// edge-selection logic as [Node.InsertRoute] but without creating or splitting
// any node. It returns the endpoint already registered for method at the exact
// pattern location, or (nil, false) when an InsertRoute of pattern would
// instead build new structure (a fresh child or a node split) — in which case
// no endpoint can pre-exist there.
//
// It is the read-only twin of the duplicate check in setEndpoint: a non-nil,
// non-auto-generated result means InsertRoute(method, pattern) would return a
// [DuplicateRouteError]. Parameter names play no part in navigation — a
// pattern reaches the same node under any names — so an endpoint registered as
// "/users/{id}" is found for "/users/{name}". FindEndpoint reports only
// endpoint existence; it does not surface the structural conflicts (a second
// regexp matcher at one level, or a mismatched regexp tail) that InsertRoute
// also rejects — a mismatch during navigation simply yields (nil, false), since
// no endpoint exists at the resulting location.
func (n *Node[V]) FindEndpoint(method MethodTyp, pattern string) (*Endpoint[V], bool) {
	search := pattern

	for {
		if len(search) == 0 {
			ep, ok := n.Endpoints[method]
			return ep, ok
		}

		if search[0] == '{' {
			seg, err := patNextSegment(search)
			if err != nil {
				return nil, false
			}
			child := n.findParamChild(seg)
			if child == nil {
				return nil, false
			}
			n = child
			search = seg.Suffix
			continue
		}

		// Static segment — follow the edge by first byte.
		child := n.Children[NtStatic].FindEdge(search[0])
		if child == nil {
			return nil, false
		}
		commonLen := longestPrefix(search, child.Prefix)
		if commonLen < len(child.Prefix) {
			// InsertRoute would split child into an intermediate node, so no
			// endpoint exists at the exact pattern yet.
			return nil, false
		}
		n = child
		search = search[commonLen:]
	}
}

// findParamChild returns the existing parameter, catch-all, or regexp child
// that matches seg's shape, or nil if none does. Names are not compared: a
// node has at most one parameter child and one catch-all child, and a regexp
// child is identified by its matcher alone. It is the read-only counterpart of
// [Node.findOrUpdateParamChild]: it never updates a regexp tail and never
// reports a conflict — a matcher mismatch simply yields nil, because an
// InsertRoute would then reject the pattern, which is not an endpoint already
// present at the matched location.
func (n *Node[V]) findParamChild(seg PatternSegment) *Node[V] {
	children := n.Children[seg.Kind]

	switch seg.Kind {
	case NtParam, NtCatchAll:
		if len(children) == 0 {
			return nil
		}
		return children[0]

	case NtRegexp:
		for _, ch := range children {
			if ch.RegexpSeg == nil || ch.RegexpSeg.Regexp == nil {
				continue
			}
			if ch.RegexpSeg.Regexp.String() == seg.Regexp.String() {
				return ch
			}
		}
	}

	return nil
}

// findOrUpdateParamChild finds the existing dynamic child that shares seg's
// shape, or returns nil if none exists. Parameter names never conflict — they
// are endpoint-owned — so a parameter or catch-all child is shared by every
// pattern with a dynamic segment at this level, and a regexp child by every
// pattern with the same matcher. For regexp nodes with a matching pattern, it
// may update the existing node's TailByte if previously unset (hence "OrUpdate"
// in the name).
func (n *Node[V]) findOrUpdateParamChild(seg PatternSegment, segmentPattern, fullPattern string) (*Node[V], error) {
	children := n.Children[seg.Kind]

	switch seg.Kind {
	case NtParam, NtCatchAll:
		if len(children) == 0 {
			return nil, nil
		}
		return children[0], nil

	case NtRegexp:
		for _, ch := range children {
			if ch.RegexpSeg == nil || ch.RegexpSeg.Regexp == nil {
				continue
			}

			sameMatcher := ch.RegexpSeg.Regexp.String() == seg.Regexp.String()
			if !sameMatcher {
				continue
			}

			if ch.Tail != 0 && seg.TailByte != 0 && ch.Tail != seg.TailByte {
				return nil, fmt.Errorf(
					"radix: conflicting regexp tail %q with existing %q; existing route %q; new route %q",
					seg.TailByte, ch.Tail, ch.firstEndpointPattern(), fullPattern)
			}

			if ch.Tail == 0 && seg.TailByte != 0 {
				ch.Tail = seg.TailByte
			}

			return ch, nil
		}

		if len(children) > 0 {
			return nil, fmt.Errorf(
				"radix: conflicting regexp segment %q; existing route %q; "+
					"new route %q; only one regexp matcher is allowed at the same path level",
				segmentPattern, children[0].firstEndpointPattern(), fullPattern)
		}
	}

	return nil, nil
}

func (n *Node[V]) firstEndpointPattern() string {
	if n == nil {
		return ""
	}
	for _, method := range []MethodTyp{
		MConnect, MDelete, MGet, MHead, MOptions, MPatch, MPost, MPut, MTrace, MQuery, mStub,
	} {
		if ep, ok := n.Endpoints[method]; ok {
			return ep.Pattern
		}
	}
	for _, children := range n.Children {
		for _, child := range children {
			if pattern := child.firstEndpointPattern(); pattern != "" {
				return pattern
			}
		}
	}
	return ""
}

// FindRoute traverses the tree to find the payload registered for the given
// method and path. It populates rctx with matched parameters: values are
// captured positionally while descending (and dropped again when a branch
// backtracks), and the matched endpoint's ParamKeys are appended to
// rctx.Params.Keys on success, so Keys and Values line up only for a match.
// The boolean reports whether a route matched; when it is false,
// rctx.MethodNotAllowed tells a 404 apart from a 405.
func (n *Node[V]) FindRoute(rctx *RouteContext, method MethodTyp, path string) (V, bool) {
	v, found, _ := n.findRoute(rctx, method, path)
	return v, found
}

func (n *Node[V]) findRoute(rctx *RouteContext, method MethodTyp, path string) (v V, found, methodNotAllowed bool) {
	// Base case: path fully consumed
	if len(path) == 0 {
		if n.isLeaf() {
			if h, ok := n.resolveEndpoint(rctx, method); ok {
				return h, true, false
			}
			// Method not allowed — record allowed methods
			rctx.MethodNotAllowed = true
			return v, false, true
		}
		return v, false, false
	}

	// Search static children first (highest priority)
	for _, child := range n.Children[NtStatic] {
		if child.Label != path[0] {
			continue
		}

		if len(path) >= len(child.Prefix) && path[:len(child.Prefix)] == child.Prefix {
			h, ok, mna := child.findRoute(rctx, method, path[len(child.Prefix):])
			if ok || mna {
				return h, ok, mna
			}
		}
	}

	// Search regexp children
	for _, child := range n.Children[NtRegexp] {
		if child.RegexpSeg == nil || child.RegexpSeg.Regexp == nil {
			continue
		}

		// The raw candidate ends at the tail byte or the next slash; the
		// constraint then applies to the whole decoded value, so an encoded
		// delimiter (%2F, %2D) is data and "%31" satisfies "[0-9]+".
		end := wirepath.CandidateEnd(path, child.Tail)
		if end == 0 {
			continue // empty parameter value: skip
		}
		value, ok := decodeCapture(rctx, path[:end])
		if !ok || !child.RegexpSeg.Regexp.MatchString(value) {
			continue
		}
		rest := path[end:]

		rctx.Params.Values = append(rctx.Params.Values, value)
		h, ok, mna := child.findRoute(rctx, method, rest)
		if ok || mna {
			return h, ok, mna
		}
		// Backtrack: drop the captured value
		rctx.Params.Values = rctx.Params.Values[:len(rctx.Params.Values)-1]
	}

	// Search param children
	for _, child := range n.Children[NtParam] {
		paramEnd := wirepath.CandidateEnd(path, child.Tail)
		if paramEnd == 0 {
			continue // empty parameter value: skip
		}
		value, ok := decodeCapture(rctx, path[:paramEnd])
		if !ok {
			continue
		}
		rest := path[paramEnd:]

		rctx.Params.Values = append(rctx.Params.Values, value)
		h, ok, mna := child.findRoute(rctx, method, rest)
		if ok || mna {
			return h, ok, mna
		}
		// Backtrack: drop the captured value
		rctx.Params.Values = rctx.Params.Values[:len(rctx.Params.Values)-1]
	}

	// Search the catch-all child (lowest priority).
	// Invariant: a node has at most one catch-all child (enforced at insert,
	// since two catch-all patterns at the same position conflict), so index
	// directly rather than looping. Mirrors the upstream chi nds[0] form.
	if cc := n.Children[NtCatchAll]; len(cc) > 0 {
		child := cc[0]
		// Catch-all consumes the rest of the path; slashes stay separators and
		// each encoded segment decodes once.
		value, ok := decodeCapture(rctx, path)
		if !ok {
			return v, false, false
		}
		rctx.Params.Values = append(rctx.Params.Values, value)
		if h, ok := child.resolveEndpoint(rctx, method); ok {
			return h, true, false
		}
		// Method not allowed on catch-all
		rctx.MethodNotAllowed = true
		rctx.Params.Values = rctx.Params.Values[:len(rctx.Params.Values)-1]
		return v, false, true
	}

	return v, false, false
}

// canonicalPattern brings the literal text of a pattern to the canonical wire
// form the tree matches against (see [wirepath.Static]); parameter
// definitions are copied verbatim. A pattern without a percent sign is
// returned as is.
func canonicalPattern(pattern string) (string, error) {
	if strings.IndexByte(pattern, '%') < 0 {
		return pattern, nil
	}
	var b strings.Builder
	rest := pattern
	for {
		seg, err := patNextSegment(rest)
		if err != nil {
			return "", err
		}
		b.WriteString(wirepath.Static(seg.Prefix))
		if seg.Kind == NtStatic {
			return b.String(), nil
		}
		definition := rest[:len(rest)-len(seg.Suffix)]
		b.WriteString(definition[len(seg.Prefix):])
		rest = seg.Suffix
	}
}

// decodeCapture percent-decodes one canonical parameter candidate exactly
// once. The candidate comes from the canonical wire path (see
// [wirepath.Canonical]): only reserved characters and "%" remain escaped, so
// a candidate without a percent sign only needs the UTF-8 check when the path
// was canonicalized (rctx.Canonical) and may carry raw octets. A malformed escape
// or a value that is not valid UTF-8 marks rctx.InvalidCapture and reports
// false so the caller skips the candidate.
func decodeCapture(rctx *RouteContext, raw string) (string, bool) {
	if strings.IndexByte(raw, '%') < 0 {
		if rctx.Canonical && !utf8.ValidString(raw) {
			rctx.InvalidCapture = true
			return "", false
		}
		return raw, true
	}
	value, err := url.PathUnescape(raw)
	if err != nil || !utf8.ValidString(value) {
		rctx.InvalidCapture = true
		return "", false
	}
	return value, true
}

// isLeaf returns true if this node has at least one endpoint registered.
func (n *Node[V]) isLeaf() bool {
	return len(n.Endpoints) > 0
}

// resolveEndpoint returns the payload for the given method and, on a match,
// names the positionally captured values with the endpoint's ParamKeys.
// Also collects allowed methods for 405 responses.
func (n *Node[V]) resolveEndpoint(rctx *RouteContext, method MethodTyp) (V, bool) {
	// Direct endpoint lookup
	if ep, ok := n.Endpoints[method]; ok {
		rctx.RoutePatterns = append(rctx.RoutePatterns, ep.Pattern)
		rctx.Params.Keys = append(rctx.Params.Keys, ep.ParamKeys...)
		return ep.Value, true
	}

	// Stub endpoint (any method)
	if ep, ok := n.Endpoints[mStub]; ok {
		rctx.RoutePatterns = append(rctx.RoutePatterns, ep.Pattern)
		rctx.Params.Keys = append(rctx.Params.Keys, ep.ParamKeys...)
		return ep.Value, true
	}

	// Collect allowed methods for 405 response
	for mtyp := range n.Endpoints {
		if mtyp != mStub {
			rctx.setMethodsAllowed(rctx.MethodsAllowed() | mtyp)
		}
	}

	var zero V
	return zero, false
}

// DuplicateRouteError reports an attempt to register a method+pattern that
// already has an explicit (non-auto-generated) endpoint. Patterns are compared
// by name-stripped shape — "/users/{id}" and "/users/{name}" are the same
// route — so ExistingPattern may spell its parameters differently from
// Pattern. Existing is the payload of the prior registration, so a caller that
// knows V's concrete type can surface registration-site detail (e.g. the
// original file:line) that the generic tree itself cannot read.
type DuplicateRouteError[V any] struct {
	// Method is the HTTP method of the conflicting registration.
	Method MethodTyp
	// Pattern is the pattern being registered now.
	Pattern string
	// ExistingPattern is the pattern the prior endpoint was registered as
	// (may differ from Pattern in parameter names, or when both normalize to
	// the same node).
	ExistingPattern string
	// Existing is the prior endpoint's payload.
	Existing V
}

func (e *DuplicateRouteError[V]) Error() string {
	return fmt.Sprintf("radix: duplicate route for method %s pattern %q (already registered as %q)",
		methodName(e.Method), e.Pattern, e.ExistingPattern)
}

// setEndpoint registers a payload for the given method on this node.
// paramKeys are the endpoint's parameter names in capture order.
// If autoGenerated is true, the endpoint is marked as auto-generated.
// An auto-generated endpoint can be silently replaced by any new registration.
// A non-auto-generated (explicit) endpoint returns a [DuplicateRouteError] that
// carries the conflicting prior payload.
func (n *Node[V]) setEndpoint(method MethodTyp, value V, pattern string, paramKeys []string, autoGenerated bool) error {
	if existing, exists := n.Endpoints[method]; exists {
		if !existing.AutoGenerated {
			return &DuplicateRouteError[V]{
				Method:          method,
				Pattern:         pattern,
				ExistingPattern: existing.Pattern,
				Existing:        existing.Value,
			}
		}
		// Auto-generated endpoint — allow overwrite.
	}

	n.Endpoints[method] = &Endpoint[V]{
		Value:         value,
		Pattern:       pattern,
		AutoGenerated: autoGenerated,
		ParamKeys:     paramKeys,
	}

	return nil
}

func methodName(method MethodTyp) string {
	if names := MethodTypToString(method); len(names) == 1 {
		return names[0]
	}
	return fmt.Sprintf("%d", method)
}

// addChild adds a child node and re-sorts the children of that type.
func (n *Node[V]) addChild(child *Node[V]) {
	n.Children[child.Typ] = append(n.Children[child.Typ], child)
	n.Children[child.Typ].Sort()
}

// replaceChild replaces a child that starts with the given label.
func (n *Node[V]) replaceChild(label byte, child *Node[V]) {
	for i, ch := range n.Children[NtStatic] {
		if ch.Label == label {
			n.Children[NtStatic][i] = child
			n.Children[NtStatic].Sort()
			return
		}
	}
}

// longestPrefix returns the length of the longest common prefix
// between two strings.
func longestPrefix(a, b string) int {
	n := min(len(a), len(b))
	for i := range n {
		if a[i] != b[i] {
			return i
		}
	}
	return n
}
