// Copyright (c) 2015-present Peter Kieltyka (https://github.com/pkieltyka), Google Inc.
// Originally derived from github.com/go-chi/chi (MIT License).

package credo

import (
	"fmt"
	"sync"

	"github.com/credo-go/credo/internal/radix"
)

// Routes describes the interface for route introspection.
type Routes interface {
	// Routes returns a slice of RouteInfo for all registered routes.
	Routes() []RouteInfo
}

// RouteInfo holds introspection data about a registered route.
type RouteInfo struct {
	Method  string
	Pattern string
	Host    string // host pattern (empty for default mux)
}

// routeStore is a shared registry for route introspection.
type routeStore struct {
	mu     sync.RWMutex
	routes []RouteInfo
}

func (rs *routeStore) add(ri RouteInfo) {
	rs.mu.Lock()
	for i, existing := range rs.routes {
		if existing.Method == ri.Method && existing.Pattern == ri.Pattern && existing.Host == ri.Host {
			rs.routes[i] = ri
			rs.mu.Unlock()
			return
		}
	}
	rs.routes = append(rs.routes, ri)
	rs.mu.Unlock()
}

func (rs *routeStore) snapshot() []RouteInfo {
	rs.mu.RLock()
	defer rs.mu.RUnlock()
	cp := make([]RouteInfo, len(rs.routes))
	copy(cp, rs.routes)
	return cp
}

// mux is a radix-tree backed route storage. It handles insertion and
// introspection only — dispatching is done by App.dispatch.
type mux struct {
	// tree is the radix tree root node; payloads are *routeHandler.
	tree *radix.Node[*routeHandler]

	// pool reuses RouteContext instances.
	pool *pool[*radix.RouteContext]

	// store is the shared route registry for introspection.
	store *routeStore

	// handlers lists every inserted payload so compileRoutes can build
	// per-route chains without going through the introspection store.
	handlers []*routeHandler
}

// newMux creates a new mux with an empty radix tree.
func newMux() *mux {
	mx := &mux{
		tree:  radix.NewTree[*routeHandler](),
		store: &routeStore{},
	}
	mx.pool = newPool(func() *radix.RouteContext {
		rctx := &radix.RouteContext{}
		// Pre-allocate param slices to avoid repeated small allocations
		// during route matching. Most routes have 1-4 parameters.
		rctx.Params.Keys = make([]string, 0, 4)
		rctx.Params.Values = make([]string, 0, 4)
		return rctx
	})
	return mx
}

// insert registers a route payload for the given method and pattern in the
// radix tree. If autoGenerated is true, the endpoint is marked as
// auto-generated and can be overwritten by explicit registrations.
func (mx *mux) insert(method, pattern string, rh *routeHandler, autoGenerated ...bool) {
	mtyp, ok := radix.LookupMethod(method)
	if !ok {
		panic(fmt.Sprintf("credo: unknown method %q", method))
	}

	_, err := mx.tree.InsertRoute(mtyp, pattern, rh, autoGenerated...)
	if err != nil {
		panic(fmt.Sprintf("credo: %v", err))
	}

	mx.handlers = append(mx.handlers, rh)
	mx.store.add(RouteInfo{
		Method:  method,
		Pattern: pattern,
		Host:    routeInfoHost(rh),
	})
}

// tryInsert is like insert but returns false instead of panicking on duplicate
// route errors. Used by addHeadRoute to silently skip if an explicit HEAD
// route already exists.
func (mx *mux) tryInsert(method, pattern string, rh *routeHandler, autoGenerated bool) bool {
	mtyp, ok := radix.LookupMethod(method)
	if !ok {
		return false
	}

	_, err := mx.tree.InsertRoute(mtyp, pattern, rh, autoGenerated)
	if err != nil {
		return false
	}

	mx.handlers = append(mx.handlers, rh)
	mx.store.add(RouteInfo{
		Method:  method,
		Pattern: pattern,
		Host:    routeInfoHost(rh),
	})
	return true
}

func routeInfoHost(rh *routeHandler) string {
	if rh.route != nil {
		return rh.route.hostPattern
	}
	return ""
}

// Routes returns all registered routes for introspection.
// The returned slice is a defensive copy.
func (mx *mux) Routes() []RouteInfo {
	return mx.store.snapshot()
}

// joinPath joins a prefix and pattern, ensuring exactly one slash between them.
func joinPath(prefix, pattern string) string {
	if prefix == "" {
		return pattern
	}
	if pattern == "" {
		return prefix
	}
	if prefix[len(prefix)-1] == '/' && pattern[0] == '/' {
		return prefix + pattern[1:]
	}
	if prefix[len(prefix)-1] != '/' && pattern[0] != '/' {
		return prefix + "/" + pattern
	}
	return prefix + pattern
}
